services:
  - type: web
    name: ai-crop-disease-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9